# Tier 2 COFF corpus byte-identity matrix (issue #28, part of #6).
#
# For each mode (no-LTO via MSVC cl.exe, ThinLTO and full-LTO via the pinned clang-cl), compiles the
# corpus in tests/tier2/, then links tier2lib.dll (with its import library) and tier2.exe (which
# delay-loads that DLL) through each linker side, twice. It asserts that the EXE, PDB, DLL, DLL PDB
# and import library are byte-identical run-vs-run and across sides, then runs the EXE natively.
#
# Sides: stock (llvm-ld-direct) and wrapper (llvm-ld-runner) always. With -ExternalLld, also the
# official release lld-link.exe (issue #30), compared against stock.
#
# Determinism rules (see #6): identical /threads and /opt:lldltojobs on every side, no
# /lldltocache, default /opt:lldltopartitions, /Brepro /manifest:no /lldignoreenv with CRT/SDK
# directories passed explicitly as /libpath:, relative inputs, and the same output paths on every
# side (the PDB embeds the command line and the EXE embeds the PDB name), copied aside afterwards.
param(
  [string]$BuildDir = 'build',
  [string[]]$Modes = @('nolto', 'thinlto', 'fulllto'),
  [string]$ExternalLld = '',
  [string]$WorkDir = 'tier2-work',
  [int]$ScaleFunctions = 3000
)
$ErrorActionPreference = 'Stop'
# Exit codes are checked explicitly, and pe_triage.py must be able to exit non-zero and still print.
$PSNativeCommandUseErrorActionPreference = $false

function Resolve-Tool([string]$name) {
  $item = Get-Item (Join-Path $BuildDir "Release/$name") -ErrorAction SilentlyContinue
  if (-not $item) { $item = Get-Item (Join-Path $BuildDir $name) }
  return $item.FullName
}
$stockLld = Resolve-Tool 'llvm-ld-direct.exe'
$runner = Resolve-Tool 'llvm-ld-runner.exe'
$triage = (Resolve-Path (Join-Path $PSScriptRoot '../tools/pe_triage.py')).Path
$corpus = (Resolve-Path (Join-Path $PSScriptRoot 'tier2')).Path

$sides = @('stock', 'wrapper')
if ($ExternalLld) {
  $ExternalLld = (Resolve-Path $ExternalLld).Path
  $sides += 'external'
}

Remove-Item Env:SOURCE_DATE_EPOCH, Env:LLD_REPRODUCE -ErrorAction SilentlyContinue
if (-not $env:LIB) { throw 'LIB is not set: run from an MSVC developer environment' }
$libPaths = @($env:LIB.Split(';') | Where-Object { $_ } | ForEach-Object { "/libpath:$_" })

function Invoke-Checked([string]$label, [scriptblock]$command) {
  & $command
  if ($LASTEXITCODE -ne 0) { throw "$label failed: $LASTEXITCODE" }
}

function Invoke-Link([string]$side, [string[]]$linkArgs) {
  switch ($side) {
    'stock' { & $stockLld winlink lld-link @linkArgs }
    'wrapper' { & $runner winlink lld-link @linkArgs }
    # argv[0] lands in the PDB's S_ENVBLOCK "exe" field. The external comparison hands llvm-ld-direct
    # the release binary's own path as argv[0] (see 'external-stock' below) so that field matches.
    'external' { & $ExternalLld @linkArgs }
    'external-stock' { & $stockLld winlink $ExternalLld @linkArgs }
  }
  if ($LASTEXITCODE -ne 0) { throw "$side link failed: $LASTEXITCODE ($($linkArgs -join ' '))" }
}

function Assert-SameArtifact([string]$left, [string]$right, [string]$label) {
  if ((Get-FileHash $left).Hash -eq (Get-FileHash $right).Hash) { return }
  Write-Host "::error::$label differs: $left vs $right"
  # A PDB is triaged through its image, which pe_triage.py reads together with both PDBs.
  $ext = [IO.Path]::GetExtension($left)
  $imageExt = if ($ext -eq '.pdb') { if ($left -like 'tier2lib-*') { '.dll' } else { '.exe' } } else { $ext }
  if ($imageExt -in '.exe', '.dll') {
    $leftPdb = [IO.Path]::ChangeExtension($left, '.pdb')
    $rightPdb = [IO.Path]::ChangeExtension($right, '.pdb')
    $triageArgs = @($triage, [IO.Path]::ChangeExtension($left, $imageExt), [IO.Path]::ChangeExtension($right, $imageExt))
    if ((Test-Path $leftPdb) -and (Test-Path $rightPdb)) { $triageArgs += @('--left-pdb', $leftPdb, '--right-pdb', $rightPdb) }
    python @triageArgs
  } else {
    Write-Host "  $left  $((Get-Item $left).Length) bytes  $((Get-FileHash $left).Hash)"
    Write-Host "  $right  $((Get-Item $right).Length) bytes  $((Get-FileHash $right).Hash)"
  }
  throw "$label differs: $left vs $right"
}

# Generated scale TU: a few thousand functions in nested namespaces (long mangled names) plus a
# function-pointer table so none of them can be discarded. Written byte-for-byte deterministically.
function Write-ScaleTU([string]$path, [int]$count) {
  $sb = [Text.StringBuilder]::new()
  [void]$sb.Append("// Generated by tests/tier2_corpus.ps1; $count functions.`n#include `"common.h`"`n")
  $expected = 0L
  for ($i = 0; $i -lt $count; $i++) {
    $mul = ($i % 7) + 1
    $expected += $mul + $i
    [void]$sb.Append("namespace tier2_scale { namespace group$([int][Math]::Floor($i / 100)) { int fn$i(int x) { return x * $mul + $i; } } }`n")
  }
  [void]$sb.Append("static int (*const scale_table[])(int) = {`n")
  for ($i = 0; $i -lt $count; $i++) {
    [void]$sb.Append("  &tier2_scale::group$([int][Math]::Floor($i / 100))::fn$i,`n")
  }
  [void]$sb.Append("};`n")
  [void]$sb.Append("int scale_check() {`n  long long sum = 0;`n  for (auto fn : scale_table) sum += fn(1);`n  return sum == ${expected}LL;`n}`n")
  [IO.File]::WriteAllText($path, $sb.ToString(), [Text.UTF8Encoding]::new($false))
}

Remove-Item $WorkDir -Recurse -Force -ErrorAction SilentlyContinue
New-Item -ItemType Directory $WorkDir | Out-Null

foreach ($mode in $Modes) {
  $modeDir = Join-Path $WorkDir $mode
  New-Item -ItemType Directory $modeDir | Out-Null
  Push-Location $modeDir
  try {
    Write-Host "=== tier2 [$mode] compile"
    switch ($mode) {
      'nolto' { $cc = 'cl'; $lto = @() }
      'thinlto' { $cc = 'clang-cl'; $lto = @('/clang:-flto=thin') }
      'fulllto' { $cc = 'clang-cl'; $lto = @('/clang:-flto') }
      default { throw "unknown mode: $mode" }
    }
    $cflags = @('/nologo', '/c', '/Brepro', '/Z7', '/MT', '/O2', '/Gy', "/I$corpus") + $lto
    $cxxflags = $cflags + @('/EHsc', '/std:c++17')
    Write-ScaleTU (Join-Path (Get-Location) 'scale.cpp') $ScaleFunctions
    $cxxUnits = @('main', 'comdat_a', 'comdat_b', 'init_a', 'init_b', 'eh', 'tls')
    foreach ($unit in $cxxUnits) {
      Invoke-Checked "$mode compile $unit" { & $cc @cxxflags (Join-Path $corpus "$unit.cpp") "/Fo:$unit.obj" }
    }
    Invoke-Checked "$mode compile scale" { & $cc @cxxflags scale.cpp '/Fo:scale.obj' }
    foreach ($unit in 'weak', 'plain') {
      Invoke-Checked "$mode compile $unit" { & $cc @cflags (Join-Path $corpus "$unit.c") "/Fo:$unit.obj" }
    }
    Invoke-Checked "$mode compile lib" { & $cc @cxxflags (Join-Path $corpus 'dll/lib.cpp') '/Fo:lib.obj' }
    Invoke-Checked "$mode assemble asm" { ml64 /nologo /c /Foasm.obj (Join-Path $corpus 'asm.asm') }

    $common = @('/threads:4', '/opt:lldltojobs=2', '/brepro', '/manifest:no', '/lldignoreenv',
      '/opt:ref', '/opt:icf', '/debug:full', '/pdbaltpath:%_PDB%', '/machine:x64') + $libPaths
    $dllArgs = $common + @('/dll', '/out:tier2lib.dll', '/implib:tier2lib.lib', '/pdb:tier2lib.pdb', 'lib.obj')
    $exeArgs = $common + @('/subsystem:console', '/out:tier2.exe', '/pdb:tier2.pdb',
      'main.obj', 'comdat_a.obj', 'comdat_b.obj', 'init_a.obj', 'init_b.obj', 'eh.obj', 'tls.obj',
      'scale.obj', 'weak.obj', 'plain.obj', 'asm.obj', 'tier2lib.lib', 'delayimp.lib', '/delayload:tier2lib.dll')
    $artifacts = @('tier2.exe', 'tier2.pdb', 'tier2lib.dll', 'tier2lib.pdb', 'tier2lib.lib')

    # One entry per (side, iteration). For the external comparison, llvm-ld-direct is run again
    # with the release binary's path as argv[0], so that pair differs only in the linker binary.
    $runs = @()
    foreach ($side in $sides) {
      if ($side -eq 'external') { $runs += @('external-stock', 'external') } else { $runs += $side }
    }
    foreach ($side in $runs) {
      foreach ($iteration in 1, 2) {
        Remove-Item $artifacts -ErrorAction SilentlyContinue
        Invoke-Link $side $dllArgs
        Invoke-Link $side $exeArgs
        foreach ($artifact in $artifacts) {
          $name = [IO.Path]::GetFileNameWithoutExtension($artifact)
          $ext = [IO.Path]::GetExtension($artifact)
          Copy-Item $artifact "$name-$side-$iteration$ext"
        }
      }
      foreach ($artifact in $artifacts) {
        $name = [IO.Path]::GetFileNameWithoutExtension($artifact)
        $ext = [IO.Path]::GetExtension($artifact)
        Assert-SameArtifact "$name-$side-1$ext" "$name-$side-2$ext" "tier2 [$mode] $artifact $side run-vs-run"
      }
    }
    foreach ($artifact in $artifacts) {
      $name = [IO.Path]::GetFileNameWithoutExtension($artifact)
      $ext = [IO.Path]::GetExtension($artifact)
      Assert-SameArtifact "$name-stock-1$ext" "$name-wrapper-1$ext" "tier2 [$mode] $artifact stock-vs-wrapper"
      if ($ExternalLld) {
        Assert-SameArtifact "$name-external-stock-1$ext" "$name-external-1$ext" "tier2 [$mode] $artifact llvm-ld-direct-vs-release-lld-link"
      }
    }
    Write-Host "tier2 [$mode]: $($artifacts -join ', ') byte-identical across $($sides -join ', ') (2 runs each)"

    # The last link left tier2.exe and tier2lib.dll side by side; all sides are identical by now.
    Invoke-Checked "tier2 [$mode] native execution" { .\tier2.exe }
  } finally {
    Pop-Location
  }
}
Write-Host "tier2: all modes passed ($($Modes -join ', '))"
